"""empty message

Revision ID: 342badf19bb5
Revises: 3695536ec7ec
Create Date: 2025-10-12 00:29:41.442007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '342badf19bb5'
down_revision: Union[str, Sequence[str], None] = '3695536ec7ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('file_uploads')
    op.add_column('datasets', sa.Column('filename', sa.String(length=255), nullable=False))
    op.add_column('datasets', sa.Column('filepath', sa.String(), nullable=False))
    op.add_column('datasets', sa.Column('content_type', sa.String(length=100), nullable=True))
    op.add_column('datasets', sa.Column('upload_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.alter_column('datasets', 'row_count',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=True,
               postgresql_using='row_count::integer')
    op.drop_column('datasets', 'path')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datasets', sa.Column('path', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('datasets', 'row_count',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('datasets', 'upload_time')
    op.drop_column('datasets', 'content_type')
    op.drop_column('datasets', 'filepath')
    op.drop_column('datasets', 'filename')
    op.create_table('file_uploads',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('filename', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('filepath', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('content_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('upload_time', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('file_uploads_pkey'))
    )
    # ### end Alembic commands ###
