"""Add fitted_model column to feature_generation_runs

Revision ID: d619cf87abdc
Revises: af1cce7ffdec
Create Date: 2025-11-16 17:16:37.785786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd619cf87abdc'
down_revision: Union[str, Sequence[str], None] = 'af1cce7ffdec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feature_generation_runs', sa.Column('fitted_model', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feature_generation_runs', 'fitted_model')
    # ### end Alembic commands ###
